# -*- coding: utf-8 -*-
"""ML2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TOfyNlpIzM2m8NgPfJ_lah5mfICUWjZ5
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

dataset = pd.read_csv('creditcard.csv')

dataset.value_counts('Class')

fraud = dataset[dataset['Class']==1]
legit = dataset[dataset['Class']==0]
print(fraud.shape,legit.shape)

legit = legit.sample(n=93)
legit.shape

new_dataset = pd.concat([legit,fraud], axis=0)
new_dataset

target = new_dataset['Class']
feature = new_dataset.drop(columns='Class')
print(feature, target)

X_TRAIN,X_TEST,Y_TRAIN,Y_TEST = train_test_split(feature,target,test_size=0.2,stratify=target,random_state=2)

model = LogisticRegression(max_iter=2000)
model.fit(X_TRAIN,Y_TRAIN)

TESTING = dataset.sample(n=5)
ttarget = TESTING['Class']
tfeature = TESTING.drop(columns='Class',axis=1)
a=model.predict(tfeature)

accr = accuracy_score(a,ttarget)
accr